services:
  api1: &api
    image: mxlange/go-api-rinha2026:latest
    environment:
      - FD_SOCKET=/run/sock/api1.sock
      - INDEX_PATH=/app/data/knn.idx
      - GOMAXPROCS=1
      - GOMEMLIMIT=48MiB
      - GOGC=200
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "165M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    <<: *api
    environment:
      - FD_SOCKET=/run/sock/api2.sock
      - INDEX_PATH=/app/data/knn.idx
      - GOMAXPROCS=1
      - GOMEMLIMIT=48MiB
      - GOGC=200

  lb:
    image: mxlange/go-api-rinha2026:latest
    command: ["/app/lb"]
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - FD_UPSTREAMS=/run/sock/api1.sock,/run/sock/api2.sock
      - WORKERS=2
      - GOMAXPROCS=1
      - GOMEMLIMIT=12MiB
      - GOGC=off
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
